- name: '{{ title }}, secrets: set facts'
  set_fact:
    group_title: '{{ title }}, secrets'
    dest_secrets_dir: '{{ app_dir }}/secrets'
    secrets_file_basename: 'secrets.yml'

- name: '{{ group_title }}: create app dir'
  become: yes
  ansible.builtin.file:
    path: '{{ dest_secrets_dir }}'
    state: directory
    recurse: yes
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'

- name: '{{ group_title }}: copy secrets files'
  become: yes
  ansible.builtin.copy:
    src: '{{ secrets_dir }}/{{ secrets_file_basename }}'
    dest: '{{ dest_secrets_dir }}/{{ secrets_file_basename }}'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'

- name: '{{ group_title }}: unset facts'
  set_fact:
    group_title:
    dest_secrets_dir:
    secrets_file_basename:
