---
- hosts: default

  remote_user: '{{ rmt_user }}'

  tasks:
    - name: 'AWS playbook: set facts'
      set_fact:
        playbook_title: 'AWS playbook'
        dns_servers: ['208.67.222.222', '208.67.220.220']

    - name: "{{ playbook_title }}: VERY IMPORTANT to speeding up SSH => add hostname '{{ ansible_hostname }}' to /etc/hosts"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^\s*127\.0\.0\.1\s+localhost\s*$'
        line: 127.0.0.1 localhost {{ ansible_hostname }}

    - import_tasks: '{{ cm_dir }}/tasks/ssh/tasks.yml'
      vars:
        title: '{{ playbook_title }}'
        TODO_TEMPLATE_ssh_port: 22
        TODO_TEMPLATE_remote_user: 'TODO-USER'
        TODO_TEMPLATE_allow_ssh_ip: 'TODO-ALLOW-SSH-IP'

    - import_tasks: './tasks/dns/systemd-resolved.yml'
      vars:
        title: '{{ playbook_title }}'
        dns_servers_line: '{{ " ".join(dns_servers) }}'

    - name: '{{ playbook_title }}: update dist'
      become: yes
      apt:
        update_cache: yes

    # TODO: fix, apparently the change is not permanent
    - import_tasks: './tasks/dns/cache.yml'
      vars:
        title: '{{ playbook_title }}'
        # dns_servers: 208.67.222.222 208.67.220.220

    - name: '{{ playbook_title }}: install packages'
      become: yes
      apt:
        pkg:
          - tree
          - make
          # For becoming a non-root user
          - acl
          # For PostgreSQL database queries using Ansible
          - python3-psycopg2
        install_recommends: no

    - name: '{{ playbook_title }}: upgrade dist'
      become: yes
      apt:
        upgrade: dist

    - import_tasks: '{{ cm_dir }}/tasks/users.yml'
      vars:
        title: '{{ playbook_title }}'

    - import_tasks: '{{ cm_dir }}/tasks/lang.yml'
      vars:
        title: '{{ playbook_title }}'
        go_basename: 'go1.17.6.linux-amd64.tar.gz'
        nodejs_basename: 'node-v16.14.0-linux-x64.tar.xz'
        nodejs_extract_dest: '/tmp/node-v16.14.0-linux-x64'

    - import_tasks: '{{ cm_dir }}/tasks/web-server-and-tls/tasks.yml'
      vars:
        title: '{{ playbook_title }}'

    - import_tasks: '{{ cm_dir }}/tasks/deploy-code.yml'
      vars:
        title: '{{ playbook_title }}'
        repo: 'https://github.com/software-engr-full-stack/domain-ip-address-mapper'

    - import_tasks: './tasks/secrets.yml'
      vars:
        title: '{{ playbook_title }}'

    - import_tasks: './tasks/app-db-init.yml'
      vars:
        title: '{{ playbook_title }}'

    - import_tasks: '{{ cm_dir }}/tasks/app/tasks.yml'
      vars:
        title: '{{ playbook_title }}'
        # # TODO: put here or in Makefile. Putting it here makes the Makefile less cluttered.
        # make_task_name_to_launch_http: 'aws-http'

    - import_tasks: '{{ cm_dir }}/tasks/reboot.yml'
      vars:
        title: '{{ playbook_title }}'

    - name: '{{ playbook_title }}: unset facts'
      set_fact:
        playbook_title:
        dns_servers:

  handlers:
  - name: restart-ssh
    become: yes
    service:
      name: ssh
      state: restarted
